# Generated by Django 4.2.4 on 2024-09-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='price',
        ),
    ]
